// background.js — Service worker that handles Claude API calls

const CLAUDE_API_URL = 'https://api.anthropic.com/v1/messages';
const CLAUDE_MODEL   = 'claude-haiku-4-5-20251001';
const MAX_TEXT_CHARS = 2500;

// ── API key cache ─────────────────────────────────────────────────────────────
// Fetching from storage on every request adds latency. Cache it and keep in
// sync via the storage.onChanged listener.

let cachedApiKey = null;

chrome.storage.sync.get(['claudeApiKey'], ({ claudeApiKey }) => {
  cachedApiKey = claudeApiKey || null;
});

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'sync' && changes.claudeApiKey) {
    cachedApiKey = changes.claudeApiKey.newValue || null;
  }
});

// ── Message handler ───────────────────────────────────────────────────────────

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'analyzePost') {
    const contentType = request.contentType === 'comment' ? 'comment' : 'post';
    analyzeWithClaude(request.text, contentType)
      .then(result => sendResponse({ success: true, ...result }))
      .catch(err  => sendResponse({ success: false, error: err.message }));
    return true; // keep channel open for async response
  }
});

// ── Claude API call ───────────────────────────────────────────────────────────

async function analyzeWithClaude(text, contentType = 'post') {
  if (!cachedApiKey) throw new Error('NO_API_KEY');

  const response = await fetch(CLAUDE_API_URL, {
    method: 'POST',
    headers: {
      'x-api-key': cachedApiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 150,
      messages: [{ role: 'user', content: buildPrompt(text, contentType) }],
    }),
  });

  if (!response.ok) {
    let msg = `API error ${response.status}`;
    try { msg = (await response.json()).error?.message || msg; } catch (_) {}
    throw new Error(msg);
  }

  const data = await response.json();
  const raw  = data.content?.[0]?.text?.trim();
  if (!raw) throw new Error('Empty response from Claude');

  return parseClaudeResponse(raw);
}

// ── Prompt builder ────────────────────────────────────────────────────────────

function buildPrompt(text, contentType = 'post') {
  const truncated = text.slice(0, MAX_TEXT_CHARS);
  const isComment = contentType === 'comment';
  const label     = isComment ? 'comment' : 'post';

  const commentContext = isComment ? `
CRITICAL CONTEXT — LinkedIn comments:
Comments are inherently short, reactive, and conversational. This is the MOST important context for scoring.

Short comments (under ~200 characters) are OVERWHELMINGLY human-written. AI tools almost never generate very short, casual replies — they produce longer, more elaborate responses. When you see a short comment, your strong default should be a LOW score (5–25) unless there is specific, compelling evidence of AI.

Examples of clearly HUMAN comments that must score BELOW 20:
- "I have 0 coding experience! Where can I register?"
- "Really interested in this. I would love to be involved if possible."
- "Great post! This resonates with me."
- "Totally agree — we saw the same thing at our company."
- "Following for the comments"
- "Love this! 🔥"
- "Can you share more details?"
- "This is exactly what I needed to hear today"

These are normal human reactions. Exclamation marks, simple questions, brief enthusiasm, tagging someone by name, expressing interest — these are all human behaviours, NOT AI signals.

AI-generated comments typically look like this (score 70+):
- Multi-paragraph responses that comprehensively address every point
- Overly structured with transitions like "Furthermore" and "Additionally"
- Generic praise that could apply to any post ("What a thoughtful and insightful perspective on this important topic")
- Suspiciously thorough summaries of the original post's arguments

Watch for these comment-specific human signals:
- Typos, abbreviations, or casual shorthand (normal in quick replies)
- Referencing specific details from the original post (shows they actually read it)
- Adding a personal anecdote or counterpoint, even briefly
- Conversational tone ("Yeah", "Honestly", "Ha", "100%")
- Exclamation marks showing genuine enthusiasm
- Mentioning someone by name
- Asking a direct question
- Domain-specific jargon used naturally in context
` : '';

  return `You are an AI-detection expert analysing a LinkedIn ${label}. Determine the likelihood (0–100) that it was generated by an AI language model rather than written by a human.

IMPORTANT CONTEXT — LinkedIn writing conventions:
LinkedIn is a professional platform where humans routinely use bullet points, emoji bullets, numbered lists, structured formatting, engagement questions ("What do you think?"), and polished grammar. These are NORMAL LinkedIn conventions and must NOT be treated as AI evidence on their own. Many skilled human writers produce clean, well-structured ${label}s. Judge the substance and voice, not the formatting.
${commentContext}
Strong AI signals (weight these heavily):
- Generic, surface-level commentary that could apply to any topic — no real insight
- Vague platitudes without concrete examples ("In today's fast-paced world", "It's important to note")
- Text that reads like a template: interchangeable nouns with identical sentence skeletons
- Unnaturally smooth transitions with no rough edges or personality
- Every paragraph the same length and cadence — mechanical rhythm
- Hedging on all sides without ever committing to a position
- Buzzword-heavy with no depth ("synergy", "leverage", "game-changer" used without specifics)
- A concluding call-to-action that feels bolted on rather than organic

Strong human signals (weight these equally heavily — any of these should significantly lower the score):
- First-person experience with specific details (named people, companies, tools, events, dates)
- Domain expertise visible through precise terminology used naturally, not performatively
- A distinctive voice — humour, frustration, sarcasm, vulnerability, self-doubt
- Opinions that take a clear stance or challenge conventional thinking
- Imperfect grammar, typos, casual phrasing, or stream-of-consciousness flow
- Self-contradiction, hedging on their OWN claims ("maybe I'm wrong", "am I jumping the gun")
- Anecdotes that would be hard to fabricate (specific client interactions, career moments)
- Emotional authenticity — genuine excitement, disappointment, or uncertainty

Calibration guide:
- 0–20: Clearly human — personal voice, specific experiences, distinctive style
- 20–40: Mostly human — well-written but with personal touches and real substance
- 40–60: Uncertain — could go either way, some generic qualities but not conclusive
- 60–80: Likely AI — generic, templated feel with little personal substance
- 80–100: Almost certainly AI — reads like a prompt output with no human fingerprint

A well-structured LinkedIn ${label} with clean grammar written by a knowledgeable human should score 15–35, NOT 60+. Format alone is never sufficient evidence of AI.

Respond with ONLY a valid JSON object — no markdown, no explanation outside it:
{"score": <integer 0-100>, "reason": "<one concise sentence>"}

LinkedIn ${label}:
"""
${truncated}
"""`;
}

// ── Response parser ───────────────────────────────────────────────────────────

function parseClaudeResponse(raw) {
  let parsed;
  try {
    const clean = raw.replace(/^```[a-z]*\n?/i, '').replace(/\n?```$/, '').trim();
    parsed = JSON.parse(clean);
  } catch (_) {
    throw new Error('Could not parse Claude response');
  }

  const rawScore = Number(parsed.score);
  if (!Number.isFinite(rawScore)) throw new Error('Invalid score in Claude response');

  const score = Math.max(0, Math.min(100, Math.round(rawScore)));
  return { score, reason: parsed.reason || '' };
}
